apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: scaling-challenge
  labels:
    app: demo-app
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      component: backend
  template:
    metadata:
      labels:
        app: demo-app
        component: backend
    spec:
      containers:
        - name: backend
          image: bluegreen-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: K8S_NAMESPACE
              value: "scaling-challenge"
            - name: FLASK_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /api/pods
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/pods
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: scaling-challenge
  labels:
    app: demo-app
    component: backend
spec:
  type: ClusterIP
  selector:
    app: demo-app
    component: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http 