apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  namespace: scaling-challenge
  labels:
    app: demo-app
    version: blue
    strategy: blue-green
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-app
      version: blue
  template:
    metadata:
      labels:
        app: demo-app
        version: blue
      annotations:
        kubernetes.io/change-cause: "Initial blue deployment"
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "blue-v1.0"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5 