apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: scaling-challenge
  labels:
    app: demo-app
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      component: frontend
  template:
    metadata:
      labels:
        app: demo-app
        component: frontend
    spec:
      containers:
        - name: frontend
          image: bluegreen-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://backend-service:5000"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: scaling-challenge
  labels:
    app: demo-app
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: demo-app
    component: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http 