apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-deployment
  namespace: scaling-challenge
  labels:
    app: demo-app
    version: rollout
    strategy: rolling-update
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: demo-app
      version: rollout
  template:
    metadata:
      labels:
        app: demo-app
        version: rollout
      annotations:
        kubernetes.io/change-cause: "Rolling update deployment"
    spec:
      containers:
      - name: demo-app
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "rollout-v2.1"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5 