apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: scaling-challenge
  labels:
    app: demo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: demo-app
  # This service will route to both blue and green pods
  # Traffic distribution can be controlled by scaling deployments 