site_name: CI/CD Chaos Workshop
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
nav:
  - Home: index.md
  - Phases:
      - Setup: phases/setup.md
      - TestContainers: phases/tests.md
      - Docker: phases/docker.md
      - Jenkins: phases/jenkins.md
      - Kubernetes: phases/k8s.md
  - Certificate: certificate.md
site_name: My Docs
