site_name: CI/CD Chaos Workshop
site_url: https://your-site-url.com
repo_url: https://github.com/vellankikoti/testcontainers-python-guide
repo_name: GitHub
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.tabs.link
    - toc.integrate
nav:
  - Home: index.md
  - Setup:
      - Setup Guide: phases/setup.md
  - TestConatiners:
      - MySQL: testcontainers/mysql.md
      - MariaDB: testcontainers/mariadb.md
      - PostgreSQL: testcontainers/postgres.md
      - MongoDB: testcontainers/mongodb.md
      - Redis: testcontainers/redis.md
  - Docker:
      - Docker Phase: phases/docker.md
  - Jenkins:
      - Jenkins Phase: phases/jenkins.md
      - "Scenario 01: Docker Build": jenkins/scenario_01_docker_build.md
      - "Scenario 02: Testcontainers": jenkins/scenario_02_testcontainers.md
      - "Scenario 03: HTML Reports": jenkins/scenario_03_html_reports.md
      - "Scenario 04: Manage Secrets": jenkins/scenario_04_manage_secrets.md
      - "Scenario 05: Deploy to EKS": jenkins/scenario_05_deploy_eks.md
  - Kubernetes:
      - Kubernetes Phase: phases/k8s.md
  - Certificate: certificate.md
