services:
  - type: web
    name: ci-cd-chaos-workshop
    env: static
    buildCommand: |
      python -m pip install --upgrade pip
      pip install mkdocs mkdocs-material mkdocs-minify-plugin
      mkdocs build
    staticPublishPath: ./site
    plan: free
    autoDeploy: true 