services:
  - type: web
    name: ci-cd-chaos-workshop
    env: static
    buildCommand: |
      python -m pip install --upgrade pip
      pip install mkdocs mkdocs-material
      mkdocs build
    staticPublishPath: ./site
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
    autoDeploy: true 