services:
  - type: web
    name: workshop-certificates
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: workshop-db
          property: connectionString
      - key: UPLOAD_FOLDER
        value: uploads
      - key: FLASK_ENV
        value: production
      - key: MAX_CONTENT_LENGTH
        value: 16777216
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: workshop-db
    databaseName: workshop_certificates
    user: workshop_user
    plan: starter 