apiVersion: v1
kind: Service
metadata:
  name: vote-app-service
  namespace: vote-app
  labels:
    app: vote-app
spec:
  selector:
    app: vote-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
    protocol: TCP
  type: NodePort