apiVersion: v1
kind: Service
metadata:
  name: secure-mysql-service
  namespace: secure-todo
  labels:
    app: secure-mysql
    tier: database
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # For AWS
    networking.gke.io/load-balancer-type: "Internal"  # For GKE
spec:
  selector:
    app: secure-mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  type: ClusterIP  # INTERNAL ONLY - Never expose database externally
  sessionAffinity: None