apiVersion: v1
kind: ServiceAccount
metadata:
  name: secure-todo-sa
  namespace: secure-todo
  labels:
    app: secure-todo-app
  annotations:
    description: "Service account for secure todo application"
automountServiceAccountToken: false  # Security best practice

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secure-todo-role
  namespace: secure-todo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
  resourceNames: ["mysql-credentials", "app-credentials"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-todo-rolebinding
  namespace: secure-todo
subjects:
- kind: ServiceAccount
  name: secure-todo-sa
  namespace: secure-todo
roleRef:
  kind: Role
  name: secure-todo-role
  apiGroup: rbac.authorization.k8s.io

---
# Network Policy for additional security (if supported)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: secure-todo-netpol
  namespace: secure-todo
spec:
  podSelector:
    matchLabels:
      app: secure-mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: secure-todo-app
    ports:
    - protocol: TCP
      port: 3306