apiVersion: v1
kind: Service
metadata:
  name: secure-todo-service
  namespace: secure-todo
  labels:
    app: secure-todo-app
    tier: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # For AWS
    networking.gke.io/load-balancer-type: "External"  # For GKE
spec:
  selector:
    app: secure-todo-app
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31001  # Conflict-free port
    protocol: TCP
    name: http
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster