# 💀 BROKEN SECRET CONFIGURATIONS
# Examples of how NOT to handle secrets

apiVersion: v1
kind: Namespace
metadata:
  name: broken-secrets-demo

---
# 💀 MISTAKE 1: Secrets in ConfigMaps (not encrypted!)
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: broken-secrets-demo
data:
  host: "mysql-service"
  username: "root"
  password: "supersecret123"  # 😱 PASSWORD IN CONFIGMAP!
  api_key: "sk-1234567890abcdef"  # 💀 API KEY EXPOSED!

---
# 💀 MISTAKE 2: Wrong secret type
apiVersion: v1
kind: Secret
metadata:
  name: broken-tls-secret
  namespace: broken-secrets-demo
type: Opaque  # 💀 SHOULD BE kubernetes.io/tls
data:
  tls.crt: <certificate-data>
  tls.key: <private-key-data>

---
# 💀 MISTAKE 3: Hardcoded secrets in deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
  namespace: broken-secrets-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
      - name: app
        image: nginx
        env:
        - name: DB_PASSWORD
          value: "hardcoded-password-123"  # 💀 NEVER DO THIS!
        - name: API_SECRET
          value: "another-hardcoded-secret"  # 😱 VISIBLE IN YAML!

---
# 💀 MISTAKE 4: Over-permissive secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: broken-secrets-demo
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]  # 💀 ALL PERMISSIONS ON ALL SECRETS!

---
# 💀 MISTAKE 5: Secret mounted as environment variable (visible in ps)
apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  namespace: broken-secrets-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          name: api-secret
          key: token  # 💀 SECRET VISIBLE IN PROCESS LIST!

---
# 💀 MISTAKE 6: No secret rotation policy
apiVersion: v1
kind: Secret
metadata:
  name: stale-secret
  namespace: broken-secrets-demo
  annotations:
    created: "2020-01-01"  # 😱 4+ YEARS OLD!
    last-rotated: "never"  # 💀 NEVER CHANGED!
type: Opaque
data:
  password: b2xkLXBhc3N3b3Jk  # old-password