apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: vote-app
  labels:
    app: vote-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: quay.io/sjbylo/flask-vote-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: db_type
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"