version: '3.8'

services:
  app:
    build: 
      context: ./scenarios/step5_success
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test
    networks:
      - chaos-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - chaos-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    networks:
      - chaos-network

networks:
  chaos-network:
    driver: bridge
