# Simple Working Voting App - WFH vs WFO
# All resources in one file for simplicity

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: voting-app

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: voting-app
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

---
# Vote App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote-app
        image: simple-vote-app:latest
        imagePullPolicy: IfNotPresent  # Build and push first
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3

---
# Vote App Service (NodePort for easy access)
apiVersion: v1
kind: Service
metadata:
  name: vote-app
  namespace: voting-app
spec:
  selector:
    app: vote-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31000
  type: NodePort
